#!/usr/bin/env python3
"""
Builds trad_to_simp.json -- a single-character traditional -> simplified
mapping -- from the character-level conversion table bundled in
opencc-python-reimplemented (Apache 2.0). Used by build_extra_sentences.py to
normalise traditional-script Tatoeba sentences into the simplified script this
app actually teaches.

WHY THIS EXISTS RATHER THAN INVERTING char_script_map.json
-----------------------------------------------------------
char_script_map.json is the *forward* map (simplified -> traditional) and is
deliberately lossy in ways that make its inverse wrong:

  * It is TW/HK-variant corrected and stroke-filtered, so it is a map of "the
    traditional glyph to show a learner", not "the traditional glyphs that
    exist". 脫 is absent from it entirely -- 脱 maps to itself after the
    variant pass -- so an inverted table silently left 摆脫 unconverted.
  * **126 of its 2,096 traditional values are themselves ordinary simplified
    characters** (了, 出, 只, 台, 吃, 合, 同, 回, 家, 床, 才, 曲, 松), each being
    the traditional counterpart of some *other* simplified character.
    Inverting wholesale would rewrite 了 in every sentence in the corpus.

OpenCC's TSCharacters.txt is the real traditional -> simplified table and has
neither problem: it is 4,113 entries against the inverse's 1,970, it contains
脫 -> 脱, and characters identical in both scripts (了, 出, 家, 著) are simply
absent, so the 126-character trap cannot arise. Where a traditional character
has several simplified candidates (56 entries, e.g. 乾 -> 干 乾, 戰 -> 战 𢧐)
the first is OpenCC's own preferred form and is the one taken -- the same
first-candidate rule build_char_script_map.py documents for the forward
direction.

This is a one-time build step, not a runtime dependency, exactly like
build_char_script_map.py and build_pinyin_readings.py: it vendors a small
tracked JSON file that the corpus build reads with plain json.load, so
build_extra_sentences.py keeps working with no network.

The Apache 2.0 licence notice for this source is already vendored as
opencc_source.LICENSE.txt by build_char_script_map.py -- same package, same
licence -- so this script does not write a second copy of it.

Usage:
    python3 build_trad_to_simp.py
"""
import io
import json
import urllib.request
import zipfile

PYPI_JSON = "https://pypi.org/pypi/opencc-python-reimplemented/json"
SOURCE_FILE = "opencc/dictionary/TSCharacters.txt"
OUTPUT = "trad_to_simp.json"


def fetch_table() -> tuple:
    """Downloads the current wheel and returns (TSCharacters text, version)."""
    with urllib.request.urlopen(PYPI_JSON, timeout=60) as response:
        meta = json.load(response)
    version = meta["info"]["version"]
    url = next(u["url"] for u in meta["urls"] if u["packagetype"] == "bdist_wheel")
    print(f"Fetching opencc-python-reimplemented {version} ...")
    with urllib.request.urlopen(url, timeout=180) as response:
        data = response.read()
    print(f"  {len(data) / 1024:.0f} KB")
    with zipfile.ZipFile(io.BytesIO(data)) as wheel:
        return wheel.read(SOURCE_FILE).decode("utf-8"), version


def parse(raw: str) -> dict:
    """
    TSCharacters.txt is tab-separated: `traditional<TAB>simp1 simp2 ...`, one
    line per character that has at least one simplified form, most common
    first. Only the first candidate is kept (see the module docstring), and
    identity lines -- a character whose simplified form is itself -- are
    dropped rather than stored as no-ops.
    """
    table = {}
    for line in raw.splitlines():
        if not line.strip():
            continue
        key, _, values = line.partition("\t")
        candidates = values.split()
        if not key or not candidates:
            continue
        if candidates[0] == key:
            continue
        table[key] = candidates[0]
    return table


def build():
    raw, version = fetch_table()
    table = parse(raw)
    payload = {
        "_source": f"opencc-python-reimplemented {version} "
                   f"({SOURCE_FILE}), Apache 2.0 -- see opencc_source.LICENSE.txt",
        "_note": "Traditional -> simplified, one entry per character that "
                 "differs; first OpenCC candidate only. Generated by "
                 "build_trad_to_simp.py. See that file for why this is not "
                 "the inverse of char_script_map.json.",
        "map": table,
    }
    with open(OUTPUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=1, sort_keys=True)
    print(f"Wrote {len(table)} traditional -> simplified entries -> {OUTPUT}")


if __name__ == "__main__":
    build()
