import csv
import json
import os
import random
import re
import threading
import unicodedata
from datetime import date, timedelta

HSK_SOURCE_FILES = ["hsk_level1and2_words_with_sentences.csv", "hsk_level3_words_with_sentences.csv"]
# Real sentences beyond the hand-curated HSK 1-3 set: 16,832 pairs filtered
# from the Tatoeba project (via manythings.org/anki, CC BY 2.0 France --
# native-speaker/proofread) down to sentences using only characters in
# master_dictionary.json. See build_extra_sentences.py for the filter and
# tatoeba_cmn_eng_source.tsv for the raw, attributed upstream data. Read
# through the same tab-delimited schema as the HSK files (only `sentence` and
# `sentence_meaning` are populated), so no reader-side changes were needed.
EXTRA_SENTENCE_FILES = ["tatoeba_sentences.csv"]
SENTENCE_SOURCE_FILES = HSK_SOURCE_FILES + EXTRA_SENTENCE_FILES

# How far suggest_new_words demotes a word whose characters are all already
# unlocked: it teaches vocabulary but unlocks no new handwriting practice.
# Applied as a multiplier on the frequency rank, so a top-50 word like 你好
# still surfaces early while a rank-3000 one drops out of reach.
KNOWN_CHARS_RANK_PENALTY = 3

# Context-aware pinyin, generated by build_pinyin_readings.py from pypinyin
# (MIT). See that script's docstring for why master_dictionary.json alone
# cannot do this job: it stores one reading per character, so the tier-1 hint
# taught `zhǎng` for the 长 in 很长.
PINYIN_READINGS_FILE = "pinyin_readings.json"

# Read-only reference data shared by every JuziEngine instance, including the
# per-account engines multi-user hosting creates. Loaded once behind a lock
# rather than per call (unlike master_dictionary/words_freq, which are small
# enough to reread): this file is ~278 KB and pinyin_for_sentence runs on
# every sentence of every generated batch.
_readings_cache = None
_readings_lock = threading.Lock()

# master_dictionary.json is now ~1.1 MB (it carries frequency_rank, hsk_level
# and stroke_count per character since August 29, 2026) and is read on paths
# that run per request, so it is cached per file path rather than reparsed
# every call. Keyed by path because each hosted account constructs its own
# engine, though in practice they all share the one dictionary.
_master_dict_cache = {}
_master_dict_lock = threading.Lock()

# How many never-before-reviewed characters may enter the due queue on any one
# day. Finding 13: every character unlocked by pasting text or adding a word
# starts with last=None, which get_due_characters counted as due immediately --
# paste a short story and "Due: 400" appears at once, unordered and uncapped,
# which is not a study plan but a wall. A cap turns the backlog into a queue;
# the characters admitted are the most frequent ones, so the wait is spent on
# the most useful characters first. Overridable per account via brain.json's
# settings.daily_new_limit, which until now was a dormant key.
DEFAULT_DAILY_NEW_LIMIT = 15

# Combining marks that NFD leaves on a toned pinyin vowel, in tone order.
# Reading the mark is more robust than a table of precomposed vowels, which
# has to enumerate ā á ǎ à ē é ě è ī í ǐ ì ō ó ǒ ò ū ú ǔ ù ǖ ǘ ǚ ǜ and the
# ń ň ǹ forms besides.
_TONE_MARKS = {"̄": 1, "́": 2, "̌": 3, "̀": 4}

# Characters that make a neighbouring 一 part of a number or an ordinal rather
# than a measured quantity, which suppresses its tone sandhi -- 一九九九年 is
# yī jiǔ jiǔ jiǔ, not yì jiǔ..., and 第一 stays yī.
_NUMERIC_NEIGHBOURS = set("零一二三四五六七八九十百千万亿两")


def _due_ratio(chinese: str, due_set: set) -> float:
    """
    What proportion of a sentence's characters are due for review.

    A proportion rather than a count, because a count is really a length
    measurement in disguise: with a due queue of any size nearly every
    sentence contains several due characters, so ranking by count reliably
    picks the longest sentence available (measured: 10.3 average characters
    picked against 6.0 available). Density asks the question actually worth
    asking -- how much of this sentence is practice I need right now.
    """
    hanzi = [c for c in chinese if "一" <= c <= "鿿"]
    if not hanzi:
        return 0.0
    return sum(1 for c in hanzi if c in due_set) / len(hanzi)


def _freshness(chinese: str, completed: dict, today: str) -> int:
    """
    How new a sentence is to this learner: 2 = never completed, 1 = completed
    before but not today, 0 = already completed today.

    Ranked above due density deliberately. A sentence finished minutes ago
    teaches almost nothing on a second pass -- the learner is recalling the
    last attempt, not the characters -- whereas an unseen sentence exercises
    the same due characters in a new context, which is the thing that actually
    generalises. Coarse tiers rather than a timestamp ordering, so that within
    "unseen" the existing due-density and shuffle behaviour still decides.
    """
    entry = completed.get(chinese)
    if not entry:
        return 2
    return 0 if entry.get("last") == today else 1


# Caps how much a single Paste Text import can contain -- a few paragraphs'
# worth, which is what the feature is actually for (unlocking characters and
# saving a handful of practice sentences). server.py's MAX_BODY_SIZE (2 MB)
# is a network-abuse guard, not a usability one: it would still let through
# text far too long to be a "sentence" worth practicing, bloating brain.json
# and tying up this account's brain_lock while segment_compounds scans it.
# Counted in characters (not bytes) so it reads the same regardless of
# encoding. English text naturally runs longer per idea than Chinese, hence
# the larger translation allowance.
MAX_IMPORT_CHINESE_CHARS = 2000
MAX_IMPORT_TRANSLATION_CHARS = 6000


class JuziEngine:
    def __init__(self, brain_path="brain.json", words_path="words_freq.json", master_dict_path="master_dictionary.json"):
        self.brain_path = brain_path
        self.words_path = words_path
        self.master_dict_path = master_dict_path
        # server.py now runs requests concurrently (ThreadingHTTPServer), so
        # brain.json's read-modify-write methods (review_character,
        # import_text_locally, add_words, generate_fresh_session) can race:
        # two threads each read the same on-disk state, mutate their own copy,
        # and whichever writes last silently wins -- the other thread's
        # update (a character's SRS progress, a saved sentence) is lost. An
        # RLock (not a plain Lock) because these methods call each other and
        # each other's read-only helpers (e.g. generate_fresh_session ->
        # pick_hsk_sentences -> load_unlocked_chars), all on the same thread;
        # a plain Lock would deadlock a thread against itself on the second
        # acquire. Every method that touches self.brain_path holds this for
        # its full read-through-write span, not just around each open().
        self.brain_lock = threading.RLock()

    def load_unlocked_chars(self) -> str:
        """Loads unlocked characters from brain.json and returns them as a single string pool."""
        try:
            with self.brain_lock:
                if not os.path.exists(self.brain_path):
                    return ""
                with open(self.brain_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    chars = list(data.get("unlocked_chars", {}).keys())
                    return "".join(chars)
        except Exception as e:
            print(f"Warning loading unlocked characters: {e}")
            return ""

    def load_master_dictionary(self) -> dict:
        """
        The static character reference: pinyin, meaning, and (since the
        frequency data was carried through from hanzi_db.csv) `freq`,
        `strokes` and `hsk`. Cached per path -- the file is ~1.1 MB and this
        runs on per-request paths.

        Treat the returned dict as read-only; every caller shares it.
        """
        cached = _master_dict_cache.get(self.master_dict_path)
        if cached is not None:
            return cached
        with _master_dict_lock:
            cached = _master_dict_cache.get(self.master_dict_path)
            if cached is not None:
                return cached
            data = {}
            if os.path.exists(self.master_dict_path):
                try:
                    with open(self.master_dict_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                except Exception as e:
                    print(f"Warning: Could not load {self.master_dict_path}: {e}")
            _master_dict_cache[self.master_dict_path] = data
            return data

    def char_frequency_rank(self, char: str) -> int:
        """
        A character's frequency rank (1 = most common), or a large sentinel if
        it isn't in the dictionary, so it sorts last without special-casing.
        """
        meta = self.load_master_dictionary().get(char)
        if not meta:
            return 10 ** 9
        return meta.get("freq") or 10 ** 9

    def daily_new_limit(self, brain_data: dict = None) -> int:
        """How many new characters this account will take on per day."""
        if brain_data is None:
            brain_data = self._read_brain()
        settings = brain_data.get("settings") or {}
        raw = settings.get("daily_new_limit", DEFAULT_DAILY_NEW_LIMIT)
        try:
            value = int(raw)
        except (TypeError, ValueError):
            return DEFAULT_DAILY_NEW_LIMIT
        return max(0, value)

    def _read_brain(self) -> dict:
        """Reads brain.json, returning {} rather than raising if it can't."""
        with self.brain_lock:
            if not os.path.exists(self.brain_path):
                return {}
            try:
                with open(self.brain_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                print(f"Error reading brain database: {e}")
                return {}

    def load_word_frequencies(self) -> dict:
        """Loads the separate static word frequency file safely."""
        if not os.path.exists(self.words_path):
            return {}
        try:
            with open(self.words_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: Could not load {self.words_path}: {e}")
            return {}

    @staticmethod
    def load_pinyin_readings() -> dict:
        """
        Loads the context-aware pinyin tables, once per process.

        Returns {"phrases": {word: [reading per char]}, "chars": {char:
        [readings, most-common first]}}. Missing file is not an error: every
        caller degrades to master_dictionary.json's single reading, which is
        exactly the pre-existing behaviour, so a clone that hasn't run
        build_pinyin_readings.py still works.
        """
        global _readings_cache
        if _readings_cache is not None:
            return _readings_cache
        with _readings_lock:
            if _readings_cache is not None:      # another thread won the race
                return _readings_cache
            data = {"phrases": {}, "chars": {}}
            if os.path.exists(PINYIN_READINGS_FILE):
                try:
                    with open(PINYIN_READINGS_FILE, "r", encoding="utf-8") as f:
                        loaded = json.load(f)
                    data = {"phrases": loaded.get("phrases", {}),
                            "chars": loaded.get("chars", {})}
                except Exception as e:
                    print(f"Warning: could not load {PINYIN_READINGS_FILE}: {e}")
            else:
                print(f"Notice: {PINYIN_READINGS_FILE} not found -- tier-1 hints "
                      f"will use one reading per character. Run "
                      f"build_pinyin_readings.py to enable context-aware pinyin.")
            _readings_cache = data
            return _readings_cache

    @staticmethod
    def _tone_of(syllable: str) -> int:
        """Tone number 1-4 of a toned pinyin syllable; 0 for neutral tone."""
        for ch in unicodedata.normalize("NFD", syllable):
            if ch in _TONE_MARKS:
                return _TONE_MARKS[ch]
        return 0

    @classmethod
    def _apply_tone_sandhi(cls, chars: list, readings: list) -> list:
        """
        Applies 不 and 一 tone sandhi in place of their citation tones.

        Finding 11: both were previously shown in citation tone regardless of
        context, so a learner reading 我不是 was taught `bù` where a speaker
        says `bú`. The rules:

          不  bù -> bú before a fourth-tone syllable. Unconditional; there is
              no exception worth encoding.
          一  yī -> yí before a fourth tone, yì before first/second/third.
              Suppressed when 一 is being *named* rather than counting: as an
              ordinal (第一), in a number (一九九九年, 十一), before a month
              (一月), or sentence-finally, where it keeps yī.

        Third-tone sandhi (你好 nǐ hǎo spoken ní hǎo) is deliberately NOT
        applied. It is real, but teaching materials and dictionaries write the
        citation tones, and a hint reading `ní` where every textbook shows
        `nǐ` would look like a bug to the learner rather than a lesson.
        """
        out = list(readings)
        for i, char in enumerate(chars):
            if char not in ("不", "一") or not out[i]:
                continue
            nxt = out[i + 1] if i + 1 < len(out) else ""
            next_tone = cls._tone_of(nxt) if nxt else 0

            if char == "不":
                if next_tone == 4:
                    out[i] = "bú"
                continue

            # 一 -- check the suppressing contexts first. These RESET to yī
            # rather than merely skipping, because the phrase table can arrive
            # with sandhi already baked in: pypinyin stores 一月 as yí yuè,
            # right for "one month" but wrong for the month name January.
            prev_char = chars[i - 1] if i > 0 else ""
            next_char = chars[i + 1] if i + 1 < len(chars) else ""
            if (prev_char == "第"
                    or prev_char in _NUMERIC_NEIGHBOURS
                    or next_char in _NUMERIC_NEIGHBOURS
                    or next_char == "月"
                    or not next_char):
                out[i] = "yī"
                continue
            if next_tone == 4:
                out[i] = "yí"
            elif next_tone in (1, 2, 3):
                out[i] = "yì"
        return out

    def pinyin_for_sentence(self, chinese: str, master_dict: dict = None) -> list:
        """
        Per-POSITION pinyin for a sentence: one entry per character of
        `chinese`, "" for punctuation and anything with no known reading.

        This is finding 10's fix. char_metadata was keyed by character, so a
        sentence using 长 in both its readings had nowhere to put the second
        one, and the reading it did store came from master_dictionary.json's
        single-reading table. Resolution order:

          1. Longest-match against the phrase table, so a character inside a
             known word takes that word's reading (行 -> háng in 银行, xíng in
             行走). Longest-match-wins mirrors segment_compounds, for the same
             reason: each position is claimed once, and the longer phrase is
             the more specific context.
          2. The character's most-common reading otherwise.
          3. master_dictionary.json's single reading, if the character is
             absent from the readings file entirely.

        Then tone sandhi is applied over the result (see _apply_tone_sandhi).
        Phrase matching runs within runs of Chinese characters so a phrase can
        never straddle punctuation, again matching segment_compounds.
        """
        chars = list(chinese)
        readings = [""] * len(chars)
        if not chars:
            return readings

        tables = self.load_pinyin_readings()
        phrases, char_table = tables["phrases"], tables["chars"]
        if master_dict is None:
            master_dict = self.load_master_dictionary()
        max_len = max((len(w) for w in phrases), default=0)

        for match in re.finditer(r"[一-龥]+", chinese):
            run, base = match.group(), match.start()
            i = 0
            while i < len(run):
                for length in range(min(max_len, len(run) - i), 1, -1):
                    hit = phrases.get(run[i:i + length])
                    if hit and len(hit) == length:
                        readings[base + i:base + i + length] = hit
                        i += length
                        break
                else:
                    char = run[i]
                    alts = char_table.get(char)
                    if alts:
                        readings[base + i] = alts[0]
                    else:
                        readings[base + i] = master_dict.get(char, {}).get("pinyin", "")
                    i += 1

        return self._apply_tone_sandhi(chars, readings)

    def attach_char_data(self, sentence: dict, unlocked_chars: dict,
                         master_dict: dict = None) -> dict:
        """
        Fills in a sentence's per-character hint data, in place.

        Writes two fields, because they answer different questions and only
        one of them can be keyed by character:

          char_metadata  {char: {pinyin, meaning}} -- the original shape, kept
                         so an older saved brain.json and any client that
                         still reads it keep working. Its `pinyin` remains the
                         single per-character reading; it cannot carry a
                         context-correct one, since a sentence using 长 twice
                         in two readings has only one slot for it. That
                         limitation is finding 10 itself.
          char_pinyin    [reading, ...] parallel to `chinese`, one entry per
                         POSITION ("" for punctuation). This is the field the
                         tier-1 hint should read.

        Both are written every time, so a sentence saved before this existed
        gains char_pinyin the next time it passes through here.
        """
        chinese = sentence.get("chinese", "")
        if master_dict is None:
            master_dict = self.load_master_dictionary()

        char_metadata = {}
        for char in chinese:
            source = unlocked_chars.get(char) or master_dict.get(char) or {}
            char_metadata[char] = {"pinyin": source.get("pinyin", ""),
                                   "meaning": source.get("meaning", "")}

        sentence["char_metadata"] = char_metadata
        sentence["char_pinyin"] = self.pinyin_for_sentence(chinese, master_dict)
        return sentence

    def readings_for_char(self, char: str) -> list:
        """
        Every attested reading for a character, most-common first.

        Used to show the alternatives when a reading is ambiguous, and to let
        callers tell a genuine polyphone from a character that simply has one
        reading. Falls back to master_dictionary.json's single entry.
        """
        alts = self.load_pinyin_readings()["chars"].get(char)
        if alts:
            return list(alts)
        single = self.load_master_dictionary().get(char, {}).get("pinyin", "")
        return [single] if single else []

    def get_due_characters(self, unlocked_chars: dict = None,
                           new_limit: int = None) -> set:
        """
        The unlocked characters due for practice right now: every reviewed
        character whose interval has elapsed, plus a *capped* intake of
        characters never reviewed before. Used to bias which practice
        sentences get picked, rather than treating the whole unlocked pool as
        equally worth practicing.

        The cap is finding 13. Every character unlocked by pasting text or
        adding a word starts with last=None, and all of them counted as due at
        once -- pasting a short story produced "Due: 400" instantly, with no
        ordering and no ceiling. That is not a study plan; it is a wall, and
        the number is demoralising rather than informative. At most
        daily_new_limit characters are now introduced per day, and because
        they are admitted in frequency order the wait is always spent on the
        most useful characters first, which is the whole point of the app.

        Characters already introduced today (see review_character, which
        stamps `introduced` on a character's first grading) count against the
        day's allowance, so finishing today's new characters does not
        immediately conjure a fresh batch.
        """
        brain_data = None
        if unlocked_chars is None:
            brain_data = self._read_brain()
            unlocked_chars = brain_data.get("unlocked_chars", {})
        if new_limit is None:
            new_limit = self.daily_new_limit(brain_data)

        today = date.today()
        today_iso = today.isoformat()
        due = set()
        never_reviewed = []
        introduced_today = 0

        for char, meta in unlocked_chars.items():
            if meta.get("introduced") == today_iso:
                introduced_today += 1

            last = meta.get("last")
            if not last:
                never_reviewed.append(char)
                continue
            try:
                last_date = date.fromisoformat(last)
            except ValueError:
                # An unparseable date means the schedule for this character is
                # meaningless, so treat it as needing review now. It is not a
                # *new* character though -- it has been seen -- so it bypasses
                # the intake cap rather than consuming a day's allowance.
                due.add(char)
                continue
            interval = meta.get("interval", 0) or 0
            if last_date + timedelta(days=interval) <= today:
                due.add(char)

        allowance = max(0, new_limit - introduced_today)
        if allowance and never_reviewed:
            never_reviewed.sort(key=self.char_frequency_rank)
            due.update(never_reviewed[:allowance])
        return due

    def new_character_backlog(self, unlocked_chars: dict = None) -> int:
        """
        How many unlocked characters have never been reviewed and are waiting
        behind the daily intake cap. Reported separately from the due count so
        the UI can say "12 due, 388 waiting" instead of the flat, discouraging
        "Due: 400" that finding 13 was about.
        """
        if unlocked_chars is None:
            unlocked_chars = self._read_brain().get("unlocked_chars", {})
        waiting = [c for c, m in unlocked_chars.items() if not m.get("last")]
        due_new = [c for c in self.get_due_characters(unlocked_chars) if c in set(waiting)]
        return max(0, len(waiting) - len(due_new))

    def review_character(self, char: str, quality: int) -> dict:
        """
        Grades a single completed character quiz and advances its SM-2
        scheduling fields (interval, factor, reps, last) in brain.json.
        quality is 0-5 recall quality (5 = perfect, no hints needed);
        the frontend derives it from how many hint tiers were used.
        Per standard SM-2, quality < 3 counts as a failed recall and resets
        the repetition streak (interval back to 1, reps back to 0) rather
        than advancing the schedule.

        SM-2 assumes at most one grading per item per day. This app can
        easily produce many more: a character often appears twice in one
        sentence (我爱我的妈妈), and the sentence bank loops forever, so a
        single sitting can grade the same character six or more times.
        Advancing on every one of those compounds the interval multiplier
        against itself (1 -> 6 -> 16 -> 45 -> 130 -> 390 days), scheduling a
        character the user has barely learned a year out. So a repeat
        grading on a day the character was already reviewed does not
        advance the schedule. A *failed* repeat still applies its lapse:
        forgetting a character later in the same session is real evidence
        that it isn't known, and ignoring it would let the loop paper over
        genuine failures.
        """
        quality = max(0, min(5, int(quality)))

        with self.brain_lock:
            brain_data = {"unlocked_chars": {}, "sentences": []}
            if os.path.exists(self.brain_path):
                try:
                    with open(self.brain_path, "r", encoding="utf-8") as f:
                        brain_data = json.load(f)
                except Exception as e:
                    print(f"Error reading brain database: {e}")

            unlocked_chars = brain_data.setdefault("unlocked_chars", {})
            entry = unlocked_chars.get(char)
            if entry is None:
                raise ValueError(f"Character '{char}' is not in the unlocked pool.")

            today = date.today().isoformat()
            already_reviewed_today = entry.get("last") == today

            # First time this character has ever been graded: record the day it
            # entered study. get_due_characters counts these against the daily
            # new-character allowance (finding 13), so working through today's
            # intake doesn't immediately pull the next batch forward.
            if not entry.get("introduced"):
                entry["introduced"] = today

            reps = entry.get("reps", 0) or 0
            interval = entry.get("interval", 0) or 0
            factor = entry.get("factor", 2.5) or 2.5

            if quality < 3:
                # A lapse always counts, including a same-day repeat.
                reps = 0
                # interval 0, not 1, so the character comes back into the due
                # set *today* rather than tomorrow. With interval 1 and `last`
                # stamped today, get_due_characters computes last + 1 day >
                # today and drops it -- so failing a character removed it from
                # today's practice, which is precisely backwards: the one
                # character the learner just demonstrably could not write was
                # the one thing excluded from the rest of the session. SM-2
                # schedules a lapse for immediate re-study, and
                # pick_hsk_sentences biases toward due characters, so 0 puts
                # it back in front of them within the same sitting. The next
                # successful review takes the reps == 0 branch and sets the
                # interval to 1 as usual, so nothing downstream changes.
                interval = 0
                factor = factor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02))
                factor = max(1.3, factor)
            elif already_reviewed_today and reps > 0:
                # Successful repeat on a day already credited: no schedule
                # change, and no ease bump either (that would inflate the
                # multiplier for every later review just as badly).
                #
                # `reps > 0` exempts a character that LAPSED earlier today,
                # which is a different situation wearing the same clothes.
                # A lapse sets reps to 0 and interval to 0 so the character
                # returns to practice immediately; if the guard also blocked
                # its recovery, writing it correctly afterwards would change
                # nothing and it would sit at interval 0 for the rest of the
                # day however well the learner then performed -- re-queued
                # with no way out. Letting the recovery through graduates it
                # to interval 1 exactly once (the next same-day success has
                # reps == 1 and takes this branch again), so the compounding
                # this guard exists to prevent still cannot happen.
                return {
                    "char": char,
                    "reps": reps,
                    "interval": interval,
                    "factor": round(factor, 2),
                    "last": entry.get("last"),
                    "counted": False,
                    "due_count": len(self.get_due_characters(unlocked_chars))
                }
            else:
                if reps == 0:
                    interval = 1
                elif reps == 1:
                    interval = 6
                else:
                    interval = round(interval * factor)
                reps += 1
                factor = factor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02))
                factor = max(1.3, factor)

            entry["reps"] = reps
            entry["interval"] = interval
            entry["factor"] = round(factor, 2)
            entry["last"] = today

            with open(self.brain_path, "w", encoding="utf-8") as f:
                json.dump(brain_data, f, ensure_ascii=False, indent=4)

            return {
                "char": char,
                "reps": reps,
                "interval": interval,
                "factor": entry["factor"],
                "last": entry["last"],
                "counted": True,
                "due_count": len(self.get_due_characters(unlocked_chars))
            }

    @staticmethod
    def prune_single_char_words(unlocked_words: dict) -> int:
        """
        Drops single-character entries from an unlocked_words map in place,
        returning how many were removed.

        Before compound detection did real segmentation, a bare substring
        scan recorded any of the corpus's 704 single-character entries that
        appeared anywhere in pasted text, so existing installs carry junk
        like 的/是/我 as "studied compound words". Called on the write paths
        so the file heals itself the next time it's saved, rather than
        needing a separate migration script.
        """
        stale = [w for w in unlocked_words if len(w) < 2]
        for word in stale:
            del unlocked_words[word]
        return len(stale)

    def segment_compounds(self, raw_text: str, word_db: dict = None) -> list:
        """
        Finds the compound words from the frequency corpus that actually occur
        in raw_text, as a list of unique words.

        This replaces a bare `word in raw_text` substring scan over all 5,007
        corpus entries, which was wrong in three separate ways:

        * 704 of those entries are *single characters*, so 的/是/我 were
          reported as "compound words the user has studied" -- and then
          recorded in brain.json as exactly that. Words here are length >= 2,
          always.
        * Overlapping matches both fired: 早上 and 上 were each reported for
          the same two characters. Longest-match-wins segmentation consumes
          the text, so each position is claimed once.
        * A substring search ignores punctuation, so a "word" could straddle
          a clause boundary (...喝热茶。他是... spanning the 。). Matching runs
          of Chinese characters means a match can never cross one.

        Greedy longest-match is not a real statistical segmenter and will
        mis-split genuinely ambiguous strings. For "which HSK words appear in
        this pasted text" that tradeoff is fine; it is not jieba.
        """
        if word_db is None:
            word_db = self.load_word_frequencies()

        # Only real corpus words are matchable: "_"-prefixed keys are metadata,
        # and single characters are what this whole method exists to exclude.
        vocab = {w for w in word_db if len(w) >= 2 and not w.startswith("_")}
        if not vocab:
            return []
        max_len = max(len(w) for w in vocab)

        found = []
        seen = set()

        # Runs of Chinese characters, so punctuation, latin text, digits, and
        # newlines all act as boundaries without having to enumerate them.
        for run in re.findall(r"[一-龥]+", raw_text):
            i = 0
            while i < len(run):
                # Longest candidate first, stopping at 2 -- range's exclusive
                # bound of 1 is what keeps single characters unmatchable.
                for length in range(min(max_len, len(run) - i), 1, -1):
                    candidate = run[i:i + length]
                    if candidate in vocab:
                        if candidate not in seen:
                            seen.add(candidate)
                            found.append(candidate)
                        i += length
                        break
                else:
                    i += 1

        return found

    def analyze_text_compounds(self, raw_text: str) -> list:
        """
        Scans text and cross-references the separate static word frequency database
        to identify high-frequency compound words present in the input.
        """
        word_db = self.load_word_frequencies()

        found_words = [
            {
                "word": word,
                "pinyin": word_db[word].get("pinyin", ""),
                "meaning": word_db[word].get("meaning", ""),
                "rank": word_db[word].get("rank", 99999),
            }
            for word in self.segment_compounds(raw_text, word_db)
        ]

        # Sort discovered words by natural corpus usage frequency rank
        found_words.sort(key=lambda x: x["rank"])
        return found_words

    @staticmethod
    def _split_lines(text: str) -> list:
        """
        Splits into non-empty, stripped lines. A paste with no newline is a
        single paragraph and stays one entry (this returns a 1-item list);
        a paste with one sentence per line is a list, and each line becomes
        its own entry. This intentionally ignores sentence-ending punctuation
        (\u3002\uff01\uff1f.!?) as a split point -- a paragraph like "\u6211\u559d\u8336\u3002\u7136\u540e\u6211\u4e0a\u73ed\u3002"
        is one continuous thought the user chose not to break onto separate
        lines, so it's saved as one sentence rather than fragmented.
        """
        return [line.strip() for line in text.strip().splitlines() if line.strip()]

    def import_text_locally(self, raw_text: str, translation_text: str = "") -> dict:
        """
        Parses raw text/sentences, extracts unique Chinese characters, pulls their
        pinyin/meanings instantly from the local master_dictionary, and updates brain.json.
        Also scans for compound words via the static word frequency database.

        If translation_text is given, also saves the pasted Chinese as practice
        sentences paired with it, into brain.json's pasted_sentences -- a
        persistent personal corpus (unlike the ephemeral `sentences` bank,
        which generate_fresh_session overwrites wholesale on every new batch)
        that pick_hsk_sentences draws from alongside the built-in corpora, so
        a user's own imported material keeps resurfacing in practice. Both
        texts are split by newline and paired by position -- a paragraph with
        no line breaks stays one entry, while a list with one sentence per
        line becomes one entry per line. If the line counts don't match
        between the two texts, pairing is ambiguous, so the whole paste is
        saved as one sentence instead of guessing an alignment.
        """
        chinese_chars = set(re.findall(r'[\u4e00-\u9fa5]', raw_text))

        with self.brain_lock:
            # Load existing brain database
            brain_data = {"unlocked_chars": {}, "unlocked_words": {}, "sentences": []}
            if os.path.exists(self.brain_path):
                try:
                    with open(self.brain_path, "r", encoding="utf-8") as f:
                        brain_data = json.load(f)
                except Exception as e:
                    print(f"Error reading brain database: {e}")

            # master_dictionary now lives in its own tracked file (master_dictionary.json),
            # not inside gitignored brain.json -- drop any stale embedded copy on save.
            brain_data.pop("master_dictionary", None)

            unlocked = brain_data.setdefault("unlocked_chars", {})
            unlocked_words = brain_data.setdefault("unlocked_words", {})

            # Rejected before pruning/compound-scanning (the expensive, input-
            # length-proportional work below) so an oversized paste costs
            # only this cheap length check, not a scan of the whole thing.
            if len(raw_text) > MAX_IMPORT_CHINESE_CHARS or len(translation_text) > MAX_IMPORT_TRANSLATION_CHARS:
                return {
                    "added_count": 0,
                    "total_unlocked_count": len(unlocked),
                    "message": (
                        f"That's too much to paste at once (max {MAX_IMPORT_CHINESE_CHARS} Chinese "
                        f"characters / {MAX_IMPORT_TRANSLATION_CHARS} translation characters). "
                        "Try a few paragraphs at a time instead."
                    ),
                }

            pruned_word_count = self.prune_single_char_words(unlocked_words)
            master = self.load_master_dictionary()

            if not chinese_chars:
                return {
                    "added_count": 0,
                    "total_unlocked_count": len(unlocked),
                    "message": "No Chinese characters found in input text."
                }

            added_count = 0
            missing_chars = []

            for char in chinese_chars:
                if char not in unlocked:
                    if char in master:
                        unlocked[char] = {
                            "pinyin": master[char].get("pinyin", ""),
                            "meaning": master[char].get("meaning", ""),
                            "interval": 0,
                            "factor": 2.5,
                            "reps": 0,
                            "last": None
                        }
                        added_count += 1
                    else:
                        missing_chars.append(char)

            # Every compound word the frequency database recognizes in the pasted
            # text is recorded in unlocked_words too, not just its individual
            # characters -- so it counts as "already studied" and won't be
            # suggested again by the Suggest Words tab.
            compounds = self.analyze_text_compounds(raw_text)
            added_word_count = 0
            for item in compounds:
                word = item["word"]
                if word not in unlocked_words:
                    unlocked_words[word] = {
                        "pinyin": item.get("pinyin", ""),
                        "meaning": item.get("meaning", ""),
                        "rank": item.get("rank", 99999),
                    }
                    added_word_count += 1

            # If a translation was pasted alongside the Chinese, save real
            # sentence pairs from it into the user's persistent pasted_sentences.
            saved_sentence_count = 0
            skipped_sentence_count = 0
            sentence_pairing_matched = None
            if translation_text and translation_text.strip():
                chinese_sentences = self._split_lines(raw_text)
                english_sentences = self._split_lines(translation_text)
                sentence_pairing_matched = bool(chinese_sentences) and len(chinese_sentences) == len(english_sentences)

                if sentence_pairing_matched:
                    pairs = list(zip(chinese_sentences, english_sentences))
                else:
                    pairs = [(raw_text.strip(), translation_text.strip())]

                pasted_sentences = brain_data.setdefault("pasted_sentences", [])
                existing_chinese = {s.get("chinese") for s in pasted_sentences}

                for chi, eng in pairs:
                    chi = re.sub(r'\s+', '', chi)
                    eng = eng.strip()
                    if not chi or not eng or chi in existing_chinese:
                        continue
                    # Every Chinese character in the sentence must already be
                    # unlockable (present in unlocked, which by now holds every
                    # character from raw_text that's in master_dictionary) --
                    # otherwise it can never be shown on the canvas with real
                    # pinyin/meaning, so the pair isn't worth saving.
                    if not all(c in unlocked for c in re.findall(r'[一-龥]', chi)):
                        skipped_sentence_count += 1
                        continue
                    pasted_sentences.append({"chinese": chi, "english": eng})
                    existing_chinese.add(chi)
                    saved_sentence_count += 1

            # Save updates back to brain.json
            with open(self.brain_path, "w", encoding="utf-8") as f:
                json.dump(brain_data, f, ensure_ascii=False, indent=4)

            total_unlocked = len(unlocked)

        msg = f"Instantly unlocked {added_count} characters locally! Total active pool: {total_unlocked}."
        if compounds:
            msg += f" Found {len(compounds)} high-frequency compound words ({added_word_count} new)."
        if missing_chars:
            msg += f" ({len(missing_chars)} chars missing from master dictionary)."
        if pruned_word_count:
            msg += f" (Cleaned up {pruned_word_count} single-character entries wrongly stored as words.)"
        if saved_sentence_count:
            msg += f" Saved {saved_sentence_count} sentence(s) to your personal practice bank."
        if skipped_sentence_count:
            msg += f" ({skipped_sentence_count} sentence(s) skipped -- contain characters outside the master dictionary.)"
        if sentence_pairing_matched is False:
            msg += " (Couldn't line up sentence boundaries between the two texts, so they were saved as one combined sentence.)"

        return {
            "added_count": added_count,
            "total_unlocked_count": total_unlocked,
            "compounds_detected": compounds,
            "added_word_count": added_word_count,
            "pruned_word_count": pruned_word_count,
            "saved_sentence_count": saved_sentence_count,
            "skipped_sentence_count": skipped_sentence_count,
            "message": msg
        }

    def suggest_new_words(self, count: int = 5) -> list:
        """
        Suggests the highest-frequency compound words from words_freq.json
        that the user hasn't already added to their vocabulary (tracked via
        brain.json's unlocked_words), so vocabulary growth follows real-world
        usage frequency rather than random order.
        """
        word_db = self.load_word_frequencies()

        with self.brain_lock:
            known_words = {}
            unlocked_chars = {}
            if os.path.exists(self.brain_path):
                try:
                    with open(self.brain_path, "r", encoding="utf-8") as f:
                        brain_data = json.load(f)
                    known_words = brain_data.get("unlocked_words", {})
                    unlocked_chars = brain_data.get("unlocked_chars", {})
                except Exception as e:
                    print(f"Error reading brain database: {e}")

        candidates = [
            {
                "word": word,
                "pinyin": meta.get("pinyin", ""),
                "meaning": meta.get("meaning", ""),
                "rank": meta.get("rank", 99999),
                # A word every one of whose characters is already unlocked is
                # still worth learning -- it teaches the compound's meaning --
                # but it buys no new practice material, so it's demoted rather than
                # dropped. The demotion is a multiplier on the frequency rank,
                # not a separate bucket: bucketing sorts *every* word that
                # unlocks a character above *every* word that doesn't, and
                # since almost all 5,007 corpus words contain some character
                # you haven't unlocked, that buries 你好 thousands of entries
                # deep -- exclusion wearing a different hat. Scaling the rank
                # keeps very common known-character words near the top while
                # still letting rarer ones fall behind.
                "_sort_rank": meta.get("rank", 99999) * (
                    1 if any(c not in unlocked_chars for c in word) else KNOWN_CHARS_RANK_PENALTY
                ),
            }
            # len >= 2 is the same filter segment_compounds applies: 704 of the
            # corpus's 5,007 entries are single characters, which is why this
            # tab used to suggest 是/我/的 as "compound words".
            for word, meta in word_db.items()
            if len(word) >= 2 and not word.startswith("_") and word not in known_words
        ]
        candidates.sort(key=lambda x: x["_sort_rank"])
        top = candidates[:count]
        for c in top:
            del c["_sort_rank"]
        return top

    def sentences_unlocked_by(self, unlocked_set: set) -> dict:
        """
        For every character NOT yet unlocked, how many corpus sentences would
        become playable if it alone were added -- i.e. sentences whose only
        missing character is that one.

        HSK mode only serves a sentence when *every* character in it is
        unlocked, so an isolated character can be perfectly frequent and still
        buy no practice at all. This is the same insight seed_brain.py uses to
        pick a starter pool (raw frequency yields all function words and zero
        playable sentences); this exposes it in the running app so the Suggest
        Characters tab can say what a character is actually worth right now.

        One pass over the corpus rather than a scan per candidate: each
        sentence with exactly one missing character credits that character.
        """
        allowed_punct = "，。！？、；：“”‘’—…"
        credit = {}
        for filename in SENTENCE_SOURCE_FILES:
            if not os.path.exists(filename):
                continue
            try:
                with open(filename, "r", encoding="utf-8") as f:
                    for row in csv.DictReader(f, delimiter="\t"):
                        chinese = (row.get("sentence") or "").replace(" ", "").strip()
                        if not chinese or not (row.get("sentence_meaning") or "").strip():
                            continue
                        missing = set()
                        for char in chinese:
                            if char in unlocked_set or char in allowed_punct:
                                continue
                            missing.add(char)
                            if len(missing) > 1:
                                break
                        if len(missing) == 1:
                            char = missing.pop()
                            credit[char] = credit.get(char, 0) + 1
            except Exception as e:
                print(f"Warning: could not read {filename}: {e}")
        return credit

    def suggest_new_characters(self, count: int = 8) -> list:
        """
        The most useful characters the user hasn't unlocked yet.

        The app's whole premise is learning to write the most frequently used
        characters, but until now the only way in was pasting text or adding a
        compound word -- there was no way to ask the direct question, "what is
        the most useful character I don't know yet?". Suggest Words answers it
        for vocabulary; this answers it for the actual practice unit.

        Ranked by frequency, but reported alongside `unlocks`, the number of
        corpus sentences that become playable the moment this character is
        added (see sentences_unlocked_by). Both numbers matter and they
        disagree often: a top-100 character that completes no sentence buys no
        practice today, while a rarer one that completes forty is immediately
        useful. Showing both lets the learner choose rather than hiding the
        trade-off behind a single opaque score.
        """
        master = self.load_master_dictionary()
        brain_data = self._read_brain()
        unlocked = brain_data.get("unlocked_chars", {})
        unlocked_set = set(unlocked)

        credit = self.sentences_unlocked_by(unlocked_set)

        candidates = []
        for char, meta in master.items():
            if char in unlocked_set:
                continue
            rank = meta.get("freq")
            if not rank:
                continue
            candidates.append({
                "char": char,
                "pinyin": meta.get("pinyin", ""),
                "meaning": meta.get("meaning", ""),
                "freq": rank,
                "strokes": meta.get("strokes"),
                "hsk": meta.get("hsk"),
                "unlocks": credit.get(char, 0),
            })

        # Frequency order, but a character that immediately opens up practice
        # sentences is surfaced ahead of an equally-ranked one that doesn't.
        candidates.sort(key=lambda c: (c["unlocks"] == 0, c["freq"]))
        return candidates[:count]

    def add_characters(self, chars: list) -> dict:
        """
        Unlocks the given characters directly, without needing a compound word
        or a paste to carry them in. Skips anything already unlocked or absent
        from master_dictionary.json (there would be no pinyin or meaning to
        show, and no way to grade it).
        """
        master = self.load_master_dictionary()

        with self.brain_lock:
            brain_data = self._read_brain()
            unlocked = brain_data.setdefault("unlocked_chars", {})
            brain_data.setdefault("unlocked_words", {})

            added, skipped = [], []
            for char in chars:
                if not isinstance(char, str) or len(char) != 1:
                    skipped.append(char)
                    continue
                if char in unlocked:
                    continue
                if char not in master:
                    skipped.append(char)
                    continue
                unlocked[char] = {
                    "pinyin": master[char].get("pinyin", ""),
                    "meaning": master[char].get("meaning", ""),
                    "interval": 0,
                    "factor": 2.5,
                    "reps": 0,
                    "last": None,
                }
                added.append(char)

            with open(self.brain_path, "w", encoding="utf-8") as f:
                json.dump(brain_data, f, ensure_ascii=False, indent=4)

            return {
                "added_chars": added,
                "skipped": skipped,
                "total_unlocked_count": len(unlocked),
                "total_due_count": len(self.get_due_characters(unlocked)),
                "new_backlog": self.new_character_backlog(unlocked),
            }

    def add_words(self, words: list) -> dict:
        """
        Adds the given compound words to brain.json's unlocked_words (so
        future suggestions skip them) and unlocks any of their individual
        characters that aren't already unlocked, so the new words are
        immediately available for handwriting practice sentences.
        """
        word_db = self.load_word_frequencies()
        master = self.load_master_dictionary()

        with self.brain_lock:
            brain_data = {"unlocked_chars": {}, "unlocked_words": {}, "sentences": []}
            if os.path.exists(self.brain_path):
                try:
                    with open(self.brain_path, "r", encoding="utf-8") as f:
                        brain_data = json.load(f)
                except Exception as e:
                    print(f"Error reading brain database: {e}")

            unlocked_words = brain_data.setdefault("unlocked_words", {})
            unlocked_chars = brain_data.setdefault("unlocked_chars", {})
            pruned_word_count = self.prune_single_char_words(unlocked_words)

            added_words = []
            rejected_single_chars = []
            added_chars = 0

            for word in words:
                meta = word_db.get(word)
                # len >= 2 guards the endpoint itself, not just the suggestions
                # feeding it: /api/suggestions/add takes an arbitrary word list
                # from the client, and a single character is a character, not a
                # compound word -- unlocked_chars is where those belong. Reported
                # back rather than dropped silently: a stale browser tab holding
                # pre-fix suggestions would otherwise submit them and be told
                # "Added 0 words" with no reason given. Single-character words are
                # a real thing (猫, 水, 茶) -- they're learned by pasting them into
                # the Paste Text tab, which unlocks them for practice directly.
                if meta and len(word) < 2:
                    rejected_single_chars.append(word)
                    continue
                if not meta or word in unlocked_words:
                    continue

                unlocked_words[word] = {
                    "pinyin": meta.get("pinyin", ""),
                    "meaning": meta.get("meaning", ""),
                    "rank": meta.get("rank", 99999),
                }
                added_words.append(word)

                for char in word:
                    if char not in unlocked_chars and char in master:
                        unlocked_chars[char] = {
                            "pinyin": master[char].get("pinyin", ""),
                            "meaning": master[char].get("meaning", ""),
                            "interval": 0,
                            "factor": 2.5,
                            "reps": 0,
                            "last": None,
                        }
                        added_chars += 1

            with open(self.brain_path, "w", encoding="utf-8") as f:
                json.dump(brain_data, f, ensure_ascii=False, indent=4)

        return {
            "added_words": added_words,
            "added_chars_count": added_chars,
            "total_unlocked_count": len(unlocked_chars),
            "total_words_count": len(unlocked_words),
            "pruned_word_count": pruned_word_count,
            "rejected_single_chars": rejected_single_chars,
        }

    # Frequency bands the progress view reports coverage against. The point of
    # the app is the most-used characters, so "how far into the frequency list
    # am I" is the single most meaningful measure of progress it can offer --
    # far more than a raw unlocked count, which says nothing about whether
    # those characters are the useful ones.
    FREQUENCY_BANDS = [100, 500, 1000, 2000, 3000, 5000]

    def progress_summary(self) -> dict:
        """
        Everything the progress view needs, in one request.

        The app accumulated a lot of state a learner could never see: SM-2
        intervals, ease factors, which characters were mature, how much of the
        frequency list was covered. All of it existed and none of it was
        visible, so there was no way to answer "am I getting anywhere?" -- the
        main thing that keeps someone going on a months-long project.
        """
        brain_data = self._read_brain()
        unlocked = brain_data.get("unlocked_chars", {})
        words = brain_data.get("unlocked_words", {})
        completed = brain_data.get("completed_sentences", {}) or {}
        master = self.load_master_dictionary()

        today = date.today()
        due = self.get_due_characters(unlocked)

        # Study stages. Thresholds follow the usual spaced-repetition reading:
        # under a week is still being learned, under three weeks is holding but
        # not proven, beyond that is genuinely retained.
        stages = {"new": 0, "learning": 0, "young": 0, "mature": 0}
        factors, intervals = [], []
        forecast = {}
        for char, meta in unlocked.items():
            last = meta.get("last")
            interval = meta.get("interval", 0) or 0
            if not last:
                stages["new"] += 1
                continue
            factors.append(meta.get("factor", 2.5) or 2.5)
            intervals.append(interval)
            if interval < 7:
                stages["learning"] += 1
            elif interval < 21:
                stages["young"] += 1
            else:
                stages["mature"] += 1
            try:
                next_due = date.fromisoformat(last) + timedelta(days=interval)
            except ValueError:
                continue
            offset = (next_due - today).days
            if 0 < offset <= 14:
                forecast[offset] = forecast.get(offset, 0) + 1

        # Coverage of the frequency list: the headline number for this app.
        ranked = [(meta.get("freq"), char) for char, meta in master.items()
                  if meta.get("freq")]
        frequency_bands = []
        for band in self.FREQUENCY_BANDS:
            in_band = [c for rank, c in ranked if rank <= band]
            known = sum(1 for c in in_band if c in unlocked)
            frequency_bands.append({"band": band, "known": known,
                                    "total": len(in_band)})

        hsk_levels = {}
        for char, meta in master.items():
            level = meta.get("hsk")
            if not level:
                continue
            bucket = hsk_levels.setdefault(level, {"level": level, "known": 0, "total": 0})
            bucket["total"] += 1
            if char in unlocked:
                bucket["known"] += 1

        return {
            "unlocked_chars": len(unlocked),
            "unlocked_words": len(words),
            "due_count": len(due),
            "new_backlog": self.new_character_backlog(unlocked),
            "daily_new_limit": self.daily_new_limit(brain_data),
            "stages": stages,
            "avg_factor": round(sum(factors) / len(factors), 2) if factors else None,
            "avg_interval": round(sum(intervals) / len(intervals), 1) if intervals else None,
            "frequency_bands": frequency_bands,
            "hsk_levels": [hsk_levels[k] for k in sorted(hsk_levels)],
            "sentences_completed_unique": len(completed),
            "sentences_completed_total": sum(
                (e.get("count", 0) or 0) for e in completed.values()),
            "playable_sentences": self.count_playable_sentences(set(unlocked)),
            "forecast": [{"in_days": d, "count": forecast.get(d, 0)}
                         for d in range(1, 15)],
        }

    def count_playable_sentences(self, unlocked_set: set) -> int:
        """
        How many corpus sentences are fully writable with the current pool.
        The practical ceiling on how much practice material exists right now,
        which is what makes the frequency-coverage numbers concrete.
        """
        allowed_punct = "，。！？、；：“”‘’—…"
        total = 0
        for filename in SENTENCE_SOURCE_FILES:
            if not os.path.exists(filename):
                continue
            try:
                with open(filename, "r", encoding="utf-8") as f:
                    for row in csv.DictReader(f, delimiter="\t"):
                        chinese = (row.get("sentence") or "").replace(" ", "").strip()
                        if not chinese or not (row.get("sentence_meaning") or "").strip():
                            continue
                        if all(c in unlocked_set or c in allowed_punct for c in chinese):
                            total += 1
            except Exception as e:
                print(f"Warning: could not read {filename}: {e}")
        return total

    def record_sentence_completion(self, chinese: str) -> dict:
        """
        Records that a sentence was written all the way through.

        Finding 12: nothing remembered what had been practiced, so batches
        re-served sentences the user had just finished, and `nextSentence`
        loops the bank forever. With a 17,000-sentence corpus the pool is
        rarely exhausted, but that was never the real complaint -- the
        complaint is that a sentence you completed a minute ago is exactly as
        likely to come back as one you have never seen.

        Stored as a count and a date per sentence, keyed by the Chinese text
        itself, so it survives the sentence bank being replaced wholesale on
        every new batch. pick_hsk_sentences reads it to prefer unseen material
        (see its freshness tier).
        """
        chinese = (chinese or "").strip()
        if not chinese:
            return {"recorded": False}

        today = date.today().isoformat()
        with self.brain_lock:
            brain_data = self._read_brain()
            completed = brain_data.setdefault("completed_sentences", {})
            entry = completed.get(chinese) or {}
            entry["count"] = (entry.get("count", 0) or 0) + 1
            entry["last"] = today
            completed[chinese] = entry

            with open(self.brain_path, "w", encoding="utf-8") as f:
                json.dump(brain_data, f, ensure_ascii=False, indent=4)

        return {"recorded": True, "chinese": chinese,
                "count": entry["count"], "last": entry["last"],
                "total_completed": len(completed)}

    def load_completed_sentences(self) -> dict:
        """The user's sentence-completion history (see record_sentence_completion)."""
        return self._read_brain().get("completed_sentences", {}) or {}

    def load_pasted_sentences(self) -> list:
        """
        Loads the user's own sentence pairs saved from the Paste Text tab
        (brain.json's pasted_sentences) -- real sentences the user pasted
        alongside a translation, persisted separately from the ephemeral
        `sentences` practice bank (which generate_fresh_session replaces
        wholesale on every new batch) so they keep resurfacing in HSK-mode
        rotation indefinitely, not just for one session.
        """
        try:
            with self.brain_lock:
                if not os.path.exists(self.brain_path):
                    return []
                with open(self.brain_path, "r", encoding="utf-8") as f:
                    return json.load(f).get("pasted_sentences", [])
        except Exception as e:
            print(f"Warning loading pasted sentences: {e}")
            return []

    def pick_hsk_sentences(self, count: int = 5) -> list:
        """
        Picks real example sentences -- from the hand-curated HSK corpora, the
        larger Tatoeba-derived corpus, and the user's own saved pasted
        sentences -- whose characters are entirely within the user's currently
        unlocked pool. No AI, no network call, no API key required. The
        user's own pasted sentences are always ranked ahead of corpus
        sentences (real content they chose to study takes priority over
        anything the offline corpus happens to contain); within each of
        those two groups, sentences that reuse characters currently due for
        SM-2 review are preferred over ones that don't, so practice
        naturally reinforces what's due.

        That preference is measured as a *proportion* of the sentence, not a
        raw count of due characters. Counting hits made length the dominant
        term by accident: a 12-character sentence mentioning four due
        characters outranked a 4-character sentence made entirely of them,
        because 4 > 1. With a due queue of any real size almost every
        sentence contains several due characters, so ranking by count
        degenerated into "always serve the longest sentence available" --
        measured on a 111-character pool, picks averaged 10.3 characters
        against a 6.0 average for the sentences actually available, and every
        pick sat at or near the 12-character maximum. That is exactly
        backwards for a beginner, who has the smallest unlocked pool and the
        least business being handed the longest sentences in it.
        """
        unlocked = self.load_unlocked_chars()
        if not unlocked:
            return []

        unlocked_set = set(unlocked)
        due_set = self.get_due_characters()
        completed = self.load_completed_sentences()
        today_iso = date.today().isoformat()
        allowed_punct = "，。！？、；：“”‘’—…"
        candidates = []
        seen_chinese = set()

        for item in self.load_pasted_sentences():
            chinese = (item.get("chinese") or "").strip()
            english = (item.get("english") or "").strip()
            if not chinese or not english or chinese in seen_chinese:
                continue
            if all(c in unlocked_set or c in allowed_punct for c in chinese):
                seen_chinese.add(chinese)
                candidates.append({"english": english, "chinese": chinese,
                                   "_fresh": _freshness(chinese, completed, today_iso),
                                   "_due_ratio": _due_ratio(chinese, due_set),
                                   "_personal": True})

        for filename in SENTENCE_SOURCE_FILES:
            if not os.path.exists(filename):
                continue
            try:
                with open(filename, "r", encoding="utf-8") as f:
                    reader = csv.DictReader(f, delimiter="\t")
                    for row in reader:
                        chinese = (row.get("sentence") or "").replace(" ", "").strip()
                        english = (row.get("sentence_meaning") or "").strip()
                        if not chinese or not english or chinese in seen_chinese:
                            continue
                        if all(c in unlocked_set or c in allowed_punct for c in chinese):
                            seen_chinese.add(chinese)
                            candidates.append({"english": english, "chinese": chinese,
                                               "_fresh": _freshness(chinese, completed, today_iso),
                                               "_due_ratio": _due_ratio(chinese, due_set),
                                               "_personal": False})
            except Exception as e:
                print(f"Warning: could not read {filename}: {e}")

        # Shuffle first so that sentences tying on the sort key come back in a
        # different order each time rather than in corpus order.
        random.shuffle(candidates)
        candidates.sort(key=lambda c: (c["_personal"], c["_fresh"], c["_due_ratio"]),
                        reverse=True)
        for c in candidates:
            del c["_due_ratio"]
            del c["_personal"]
            del c["_fresh"]
        return candidates[:count]

    def generate_fresh_session(self, count: int = 5) -> dict:
        """
        Picks a brand new batch of real example sentences -- from the local
        HSK/Tatoeba corpora and the user's own saved pasted sentences -- and
        replaces the saved sentence bank in brain.json, so a completed
        session doesn't just replay the same sentences forever. No AI, no
        network, no key needed. If no sentences come back, the existing saved
        bank is left untouched.
        """
        with self.brain_lock:
            brain_data = {"unlocked_chars": {}, "sentences": []}
            if os.path.exists(self.brain_path):
                try:
                    with open(self.brain_path, "r", encoding="utf-8") as f:
                        brain_data = json.load(f)
                except Exception as e:
                    print(f"Error reading brain database: {e}")
            unlocked_chars = brain_data.get("unlocked_chars", {})

            # pick_hsk_sentences reacquires brain_lock through its own helpers,
            # which is safe since it's an RLock, and is a fast local read with
            # no network call, so holding the lock across it doesn't stall
            # other requests.
            raw_sentences = self.pick_hsk_sentences(count=count)

            master_dict = self.load_master_dictionary()
            new_sentences = []
            for item in raw_sentences:
                sentence = {"english": item["english"], "chinese": item["chinese"]}
                self.attach_char_data(sentence, unlocked_chars, master_dict)
                new_sentences.append(sentence)

            if new_sentences:
                brain_data["sentences"] = new_sentences
                with open(self.brain_path, "w", encoding="utf-8") as f:
                    json.dump(brain_data, f, ensure_ascii=False, indent=4)

            return {
                "sentences": brain_data.get("sentences", []),
                "total_unlocked_count": len(unlocked_chars),
                # Returned so the "Due: N" badge can refresh with the new
                # batch. Without it the frontend had no due figure to apply
                # and left the badge showing whatever it read at page load,
                # which drifts further from the truth with every review.
                "total_due_count": len(self.get_due_characters(unlocked_chars)),
            }

if __name__ == "__main__":
    engine = JuziEngine()
    try:
        result = engine.import_text_locally("我喜欢学习中文。")
        print("Import Result:", result)
    except Exception as e:
        print(f"Error: {e}")
