#!/usr/bin/env python3
"""
Regression tests for the context-aware tier-1 pinyin hint (findings 10 and 11).

pinyin_readings.json is regenerated by build_pinyin_readings.py against
whatever pypinyin release is current, and its scoping and hand-authored
overrides both affect the result. A regression there is silent -- the hint
still renders, it just teaches the wrong reading, which is exactly the bug
finding 10 was about. These cases pin the behaviour that was verified by hand.

The second half validates against an independent oracle: the `sentence_pinyin`
column of the two hand-curated HSK CSVs, which the app itself never reads.
Note that column has its own errors (it says zhǎng for the 长 in 很长, dū for
the 都 in 每天都读报纸, and applies no sandhi at all), so a handful of
disagreements are the CSV being wrong, not this code. The threshold is set to
catch a real regression, not to demand perfection.

Usage:  python3 test_pinyin_readings.py      (exit 0 = pass, 1 = failure)
"""
import csv
import re
import sys

from juzi_engine import JuziEngine

# (sentence, expected readings for its Chinese characters, what it pins down)
CASES = [
    # --- finding 10: the reading depends on the word, not the character ---
    ("很长", ["hěn", "cháng"], "the finding's own example: 长 is cháng here"),
    ("长大", ["zhǎng", "dà"], "...and zhǎng here, same character"),
    ("这个地方", ["zhè", "ge", "dì", "fāng"], "地 is dì inside 地方"),
    ("慢慢地走", ["màn", "màn", "de", "zǒu"], "adverbial 地 is de"),
    ("他认真地学习汉语", ["tā", "rèn", "zhēn", "de", "xué", "xí", "hàn", "yǔ"],
     "adverbial 地 after a two-syllable adjective"),
    ("更好地了解", ["gèng", "hǎo", "de", "liǎo", "jiě"], "更好地, not 好地方"),
    ("好地方", ["hǎo", "dì", "fāng"], "...and 好地方 still wins as the longer match"),
    ("我的书", ["wǒ", "de", "shū"], "的 as the possessive particle"),
    ("目的", ["mù", "dì"], "的 as dì in 目的"),
    ("银行", ["yín", "háng"], "行 is háng in 银行"),
    ("行走", ["xíng", "zǒu"], "...and xíng in 行走"),
    ("他着急", ["tā", "zháo", "jí"], "着 is zháo in 着急"),
    ("穿着", ["chuān", "zhe"], "...and zhe in 穿着"),
    ("跟著他走", ["gēn", "zhe", "tā", "zǒu"],
     "著 is the traditional 着 wherever it appears in this corpus"),
    ("每个人都会说谎", ["měi", "gè", "rén", "dōu", "huì", "shuō", "huǎng"],
     "都会 is dōu huì here, not the noun dū huì"),
    ("很多客人参加了他的生日聚会",
     ["hěn", "duō", "kè", "rén", "cān", "jiā", "le", "tā", "de",
      "shēng", "rì", "jù", "huì"],
     "word boundaries: 客人 must block 人参 from matching across it"),

    # --- finding 11: tone sandhi ---
    ("我不是他", ["wǒ", "bú", "shì", "tā"], "不 becomes bú before a fourth tone"),
    ("不好", ["bù", "hǎo"], "...and stays bù before a third"),
    ("一个人", ["yí", "gè", "rén"], "一 becomes yí before a fourth tone"),
    ("一天", ["yì", "tiān"], "...yì before a first"),
    ("他有一本书", ["tā", "yǒu", "yì", "běn", "shū"], "...yì before a third"),
    ("第一", ["dì", "yī"], "...but stays yī as an ordinal"),
    ("一九九九年", ["yī", "jiǔ", "jiǔ", "jiǔ", "nián"], "...and inside a number"),
    ("一月", ["yī", "yuè"], "...and before a month, even though upstream says yí"),
    ("十一月", ["shí", "yī", "yuè"], "...including within a longer date"),
]

HSK_CSVS = ["hsk_level1and2_words_with_sentences.csv",
            "hsk_level3_words_with_sentences.csv"]
MIN_ORACLE_AGREEMENT = 0.99


def is_hanzi(c):
    return "一" <= c <= "鿿"


def check_cases(engine):
    failures = []
    for sentence, expected, why in CASES:
        got = [p for p in engine.pinyin_for_sentence(sentence) if p]
        if got != expected:
            failures.append(f"  {sentence}\n"
                            f"    got  {' '.join(got)}\n"
                            f"    want {' '.join(expected)}\n"
                            f"    ({why})")
    print(f"hand-verified cases: {len(CASES) - len(failures)}/{len(CASES)} passing")
    for f in failures:
        print(f)
    return not failures


def check_alignment(engine):
    """char_pinyin must stay parallel to the sentence, or the hint misindexes."""
    failures = []
    for sentence, _, _ in CASES + [("你好，朋友！", [], ""), ("", [], "")]:
        readings = engine.pinyin_for_sentence(sentence)
        if len(readings) != len(sentence):
            failures.append(f"  {sentence!r}: {len(readings)} readings for "
                            f"{len(sentence)} characters")
    print(f"alignment: {'OK' if not failures else 'FAILED'} "
          f"(one reading per character, punctuation included)")
    for f in failures:
        print(f)
    return not failures


def check_against_hsk_oracle(engine):
    """Agreement with the HSK CSVs' own pinyin column, which the app never reads."""
    try:
        from audit_hsk_csvs import build_reading_table, make_aligner, base
    except ImportError:
        print("oracle: skipped (audit_hsk_csvs.py not importable)")
        return True

    align = make_aligner(build_reading_table())
    master = engine.load_master_dictionary()
    agree = disagree = 0
    for path in HSK_CSVS:
        with open(path, encoding="utf-8") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                chars = [c for c in (row.get("sentence") or "") if is_hanzi(c)]
                runs = [r for r in re.findall(
                    r"[a-zü]+", base(row.get("sentence_pinyin") or "")) if r]
                if not chars or not runs:
                    continue
                reference, _ = align(chars, runs)
                if reference is None:
                    continue
                mine = [p for p in engine.pinyin_for_sentence(
                    "".join(chars), master) if p]
                if len(mine) != len(reference):
                    continue
                for got, want in zip(mine, reference):
                    if base(got) == want:
                        agree += 1
                    else:
                        disagree += 1

    total = agree + disagree
    if not total:
        print("oracle: skipped (no comparable rows)")
        return True
    rate = agree / total
    ok = rate >= MIN_ORACLE_AGREEMENT
    print(f"HSK oracle: {rate:.2%} of {total} positions agree "
          f"(floor {MIN_ORACLE_AGREEMENT:.0%}) -- {'OK' if ok else 'FAILED'}")
    return ok


def main():
    engine = JuziEngine()
    if not engine.load_pinyin_readings()["phrases"]:
        sys.exit("pinyin_readings.json is missing or empty -- "
                 "run build_pinyin_readings.py first.")

    results = [check_cases(engine),
               check_alignment(engine),
               check_against_hsk_oracle(engine)]
    if all(results):
        print("\nAll pinyin reading tests passed.")
        return 0
    print("\nFAILURES above.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
